### ISSUE TITLE
make delegate methods optional

### ISSUE THREAD

**Issue by tereks** [nodes-ios/KeyboardHelper#22]
Hi, can I suggest to make all delegate's methods optional so if I need only one method I don't need to add another empty method

**Comment by chriscombs** [comment]
Good idea, we'll look into it. You're also welcome to make a pull request.

**Comment by daehn** [comment]
Sorry, closed this by accident. Reopened now. Not sure if marking the methods optional is possible though, as this would require them to be marked `@objc` which is not possible as their parameter is a `struct`.

**Comment by mariusc** [comment]
I think we could make it work by adding a protocol extension which implements both methods and does nothing. It's a hack, but it could probably work.

**Comment by tereks** [comment]
I think creating protocol extension is best choice.
